name: money_tracker
description: Personal money tracker - accounts, transactions, transfers, multi-currency.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.0
  http: ^1.2.0
  intl: '>=0.18.0 <1.0.0'

flutter:
  uses-material-design: true
